from __future__ import annotations

from typing import Final, Literal

SCHEMA_VERSION = "1.0"
PARSER_VERSION = "chatgpt-export/1.0"
CODEX_METADATA_PARSER_VERSION: Final[Literal["codex-local-metadata/1.0"]] = (
    "codex-local-metadata/1.0"
)
CODEX_CONTENT_PILOT_PARSER_VERSION: Final[Literal["codex-local-content-pilot/0.1"]] = (
    "codex-local-content-pilot/0.1"
)
PERSONA_STUDY_PROTOCOL_VERSION: Final[Literal["persona-study/0.1"]] = "persona-study/0.1"
POLICY_VERSION = "egress-and-authority/1.0"
REPORT_VERSION = "scientific-report/1.0"

POSTGRES_VERSION = "18.4"
PGVECTOR_VERSION = "0.8.2"
DEFAULT_LOCAL_REASONER_MODEL = "openai/gpt-oss-20b"
DEFAULT_EMBEDDING_MODEL = "BAAI/bge-m3"
DEFAULT_EMBEDDING_DIMENSIONS = 1024

DEFAULT_ARCHIVE_MAX_ENTRIES = 200_000
DEFAULT_ARCHIVE_MAX_SOURCE_BYTES = 80 * 1024**3
DEFAULT_ARCHIVE_MAX_UNCOMPRESSED_BYTES = 80 * 1024**3
DEFAULT_ARCHIVE_MAX_ENTRY_BYTES = DEFAULT_ARCHIVE_MAX_UNCOMPRESSED_BYTES
DEFAULT_ARCHIVE_MAX_JSON_ITEM_BYTES = 16 * 1024**2
DEFAULT_ARCHIVE_MAX_COMPRESSION_RATIO = 200.0
DEFAULT_JSON_MAX_NESTING = 128
DEFAULT_CONVERSATION_MAX_NODES = 10_000
DEFAULT_BRANCH_MAX_DEPTH = 2_048
DEFAULT_BRANCH_MAX_MEMBERSHIP_PAIRS = 250_000

DEFAULT_BOOTSTRAP_MAX_SOURCE_BYTES = 16 * 1024**2
DEFAULT_BOOTSTRAP_MAX_DECLARATIONS = 10_000
DEFAULT_BOOTSTRAP_MAX_STATEMENT_BYTES = 64 * 1024

DEFAULT_CODEX_INVENTORY_MAX_FILES = 100_000
DEFAULT_CODEX_INVENTORY_MAX_ENTRIES = 200_000
DEFAULT_CODEX_INVENTORY_MAX_DEPTH = 8
DEFAULT_CODEX_INVENTORY_MAX_FIRST_RECORD_BYTES = 1024**2

DEFAULT_CODEX_PILOT_MAX_FILES = 5
DEFAULT_CODEX_PILOT_MAX_TOTAL_BYTES = 16 * 1024**2
DEFAULT_CODEX_PILOT_MAX_FILE_BYTES = 4 * 1024**2
DEFAULT_CODEX_PILOT_MAX_LINE_BYTES = 1024**2
DEFAULT_CODEX_PILOT_MAX_RECORDS = 20_000
DEFAULT_CODEX_PILOT_MAX_EVENTS = 2_000
DEFAULT_CODEX_PILOT_MAX_CONTENT_BYTES = 256 * 1024

PERSONA_STUDY_MAX_FILES = 24
PERSONA_STUDY_MAX_TOTAL_BYTES = 32 * 1024**2
PERSONA_STUDY_MAX_FILE_BYTES = 4 * 1024**2
PERSONA_STUDY_MAX_RECORDS = 40_000
PERSONA_STUDY_MAX_EVENTS = 2_000
PERSONA_STUDY_RETENTION_DAYS = 7
PERSONA_HOLDOUT_MIN_FILES = 8
PERSONA_HOLDOUT_MAX_FILES = 12
PERSONA_HOLDOUT_MAX_TOTAL_BYTES = 16 * 1024**2
