<#
.SYNOPSIS
Builds one deterministic Markdown bundle from the repository's Markdown files.

.DESCRIPTION
Discovers tracked and non-ignored untracked Markdown files through Git, sorts
their repository-relative paths ordinally, and writes each source with clear
path boundaries. The generated output is excluded from its own input set.

.PARAMETER OutputPath
Optional absolute path or repository-relative output path. The default is
exports/your-next-opponent-is-you-all-markdown.md.
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$OutputPath = 'exports/your-next-opponent-is-you-all-markdown.md'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    throw 'OutputPath must not be empty or whitespace.'
}

$git = Get-Command git -ErrorAction Stop
$scriptRepoCandidate = [System.IO.Path]::GetFullPath(
    (Join-Path -Path $PSScriptRoot -ChildPath '..')
)
$repoRootResult = @(
    & $git.Source -C $scriptRepoCandidate rev-parse --show-toplevel
)
if ($LASTEXITCODE -ne 0 -or $repoRootResult.Count -ne 1) {
    throw 'Could not resolve the repository root with Git.'
}

$repoRoot = [System.IO.Path]::GetFullPath($repoRootResult[0].Trim())
if ([System.IO.Path]::IsPathRooted($OutputPath)) {
    $outputFullPath = [System.IO.Path]::GetFullPath($OutputPath)
}
else {
    $outputFullPath = [System.IO.Path]::GetFullPath(
        (Join-Path -Path $repoRoot -ChildPath $OutputPath)
    )
}

$gitMarkdownPaths = @(
    & $git.Source `
        -c core.quotepath=false `
        -C $repoRoot `
        ls-files --cached --others --exclude-standard -- '*.md'
)
if ($LASTEXITCODE -ne 0) {
    throw 'Git could not enumerate repository Markdown files.'
}

$sourcePaths = [System.Collections.Generic.List[string]]::new()
foreach ($gitPath in $gitMarkdownPaths) {
    if ([string]::IsNullOrWhiteSpace($gitPath)) {
        continue
    }

    $relativePath = $gitPath.Replace('\', '/')
    $sourceFullPath = [System.IO.Path]::GetFullPath(
        (Join-Path -Path $repoRoot -ChildPath $relativePath)
    )

    if ([System.StringComparer]::OrdinalIgnoreCase.Equals(
            $sourceFullPath,
            $outputFullPath
        )) {
        continue
    }

    if (Test-Path -LiteralPath $sourceFullPath -PathType Leaf) {
        $sourcePaths.Add($relativePath)
    }
}

$sourcePaths.Sort([System.StringComparer]::Ordinal)
if ($sourcePaths.Count -eq 0) {
    throw 'No Markdown source files were found.'
}

$builder = [System.Text.StringBuilder]::new()
$null = $builder.AppendLine('# Your Next Opponent Is You — Complete Markdown Bundle')
$null = $builder.AppendLine()
$null = $builder.AppendLine(
    '> Generated by `scripts/export-all-markdown.ps1`. Do not edit this file directly.'
)
$null = $builder.AppendLine(
    ('> Source count: {0}. Sources are ordered by repository-relative path.' -f $sourcePaths.Count)
)
$null = $builder.AppendLine()
$null = $builder.AppendLine('## Source Index')
$null = $builder.AppendLine()

for ($index = 0; $index -lt $sourcePaths.Count; $index++) {
    $displayPath = $sourcePaths[$index].Replace('`', '``')
    $null = $builder.AppendLine(
        ('{0}. `{1}`' -f ($index + 1), $displayPath)
    )
}

foreach ($relativePath in $sourcePaths) {
    $sourceFullPath = [System.IO.Path]::GetFullPath(
        (Join-Path -Path $repoRoot -ChildPath $relativePath)
    )
    $content = [System.IO.File]::ReadAllText($sourceFullPath)
    $content = $content.Replace("`r`n", "`n").Replace("`r", "`n")
    $content = $content.TrimEnd([char[]]"`r`n")
    $displayPath = $relativePath.Replace('`', '``')

    $null = $builder.AppendLine()
    $null = $builder.AppendLine('---')
    $null = $builder.AppendLine()
    $null = $builder.AppendLine(('## Source: `{0}`' -f $displayPath))
    $null = $builder.AppendLine()
    $null = $builder.AppendLine(('<!-- BEGIN SOURCE: {0} -->' -f $relativePath))
    $null = $builder.AppendLine()
    if ($content.Length -gt 0) {
        $null = $builder.AppendLine($content)
    }
    $null = $builder.AppendLine()
    $null = $builder.AppendLine(('<!-- END SOURCE: {0} -->' -f $relativePath))
}

$outputDirectory = Split-Path -Parent $outputFullPath
$null = [System.IO.Directory]::CreateDirectory($outputDirectory)
$utf8WithoutBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText(
    $outputFullPath,
    $builder.ToString().Replace("`r`n", "`n"),
    $utf8WithoutBom
)

Write-Output (
    'Bundled {0} Markdown files into {1}' -f `
        $sourcePaths.Count,
        $outputFullPath
)
